module.exports = {
  PACIENT: {
    CREATE_CHANNEL: "CREATE_PACIENTS",
    CREATE_RESPONSE_CHANNEL: "CREATE_PACIENTS_RESPONSE",
    LIST_CHANNEL: "LIST_PACIENTS",
    LIST_RESPONSE_CHANNEL: "LIST_PACIENTS_RESPONSE",
    SHOW_CHANNEL: "SHOW_PACIENTS",
    SHOW_RESPONSE_CHANNEL: "SHOW_PACIENTS_RESPONSE",
    UPDATE_CHANNEL: "UPDATE_PACIENTS",
    UPDATE_RESPONSE_CHANNEL: "UPDATE_PACIENTS_RESPONSE",
    DESTROY_CHANNEL: "DESTROY_PACIENTS",
    DESTROY_RESPONSE_CHANNEL: "DESTROY_PACIENTS_RESPONSE",
  },
};
