module.exports = {
  PACIENT: {
    CREATE_CHANNEL: "CREATE_PACIENTS",
    CREATE_RESPONSE_CHANNEL: "CREATE_PACIENTS_RESPONSE",
    LIST_CHANNEL: "LIST_PACIENTS",
    LIST_RESPONSE_CHANNEL: "LIST_PACIENTS_RESPONSE",
    SHOW_CHANNEL: "SHOW_PACIENTS",
    SHOW_RESPONSE_CHANNEL: "SHOW_PACIENTS_RESPONSE",
    UPDATE_CHANNEL: "UPDATE_PACIENTS",
    UPDATE_RESPONSE_CHANNEL: "UPDATE_PACIENTS_RESPONSE",
    DESTROY_CHANNEL: "DESTROY_PACIENTS",
    DESTROY_RESPONSE_CHANNEL: "DESTROY_PACIENTS_RESPONSE",
  },

  EVOLUTION: {
    CREATE_CHANNEL: "CREATE_EVOLUTIONS",
    CREATE_RESPONSE_CHANNEL: "CREATE_EVOLUTIONS_RESPONSE",
    LIST_CHANNEL: "LIST_EVOLUTIONS",
    LIST_RESPONSE_CHANNEL: "LIST_EVOLUTIONS_RESPONSE",
    SHOW_CHANNEL: "SHOW_EVOLUTIONS",
    SHOW_RESPONSE_CHANNEL: "SHOW_EVOLUTIONS_RESPONSE",
    UPDATE_CHANNEL: "UPDATE_EVOLUTIONS",
    UPDATE_RESPONSE_CHANNEL: "UPDATE_EVOLUTIONS_RESPONSE",
    DESTROY_CHANNEL: "DESTROY_EVOLUTIONS",
    DESTROY_RESPONSE_CHANNEL: "DESTROY_EVOLUTIONS_RESPONSE",
  },

  BED: {
    LIST_NOT_IN_USE_CHANNEL: "LIST_BEDS_NOT_IN_USE",
    LIST_NOT_IN_USE_RESPONSE_CHANNEL: "LIST_BEDS_NOT_IN_USE_RESPONSE",
  },

  INTERNSHIP: {
    LIST_INTERNSHIPS: "LIST_INTERNSHIPS_CHANNEL",
    LIST_INTERNSHIPS_RESPONSE: "LIST_INTERNSHIPS_RESPONSE_CHANNEL",

    SHOW_INTERNSHIP_CHANNEL: "SHOW_INTERNSHIP_CHANNEL",
    SHOW_INTERNSHIP_RESPONSE_CHANNEL: "SHOW_INTERNSHIP_RESPONSE_CHANNEL",

    UPDATE_CHANNEL: "UPDATE_CHANNEL",
    UPDATE_CHANNEL_RESPONSE: "UPDATE_CHANNEL_RESPONSE",
  },
};
