export default {
  PACIENT: {
    CREATE_CHANNEL: "CREATE_PACIENTS",
    CREATE_RESPONSE_CHANNEL: "CREATE_PACIENTS_RESPONSE",
    LIST_CHANNEL: "LIST_PACIENTS",
    LIST_RESPONSE_CHANNEL: "LIST_PACIENTS_RESPONSE",
    SEARCH_CHANNEL: "SEARCH_PACIENTS",
    SEARCH_RESPONSE_CHANNEL: "SEARCH_PACIENTS_RESPONSE",
    SHOW_CHANNEL: "SHOW_PACIENTS",
    SHOW_RESPONSE_CHANNEL: "SHOW_PACIENTS_RESPONSE",
    UPDATE_CHANNEL: "UPDATE_PACIENTS",
    UPDATE_RESPONSE_CHANNEL: "UPDATE_PACIENTS_RESPONSE",
    DESTROY_CHANNEL: "DESTROY_PACIENTS",
    DESTROY_RESPONSE_CHANNEL: "DESTROY_PACIENTS_RESPONSE",
  },

  EVOLUTION: {
    CREATE_CHANNEL: "CREATE_EVOLUTIONS",
    CREATE_RESPONSE_CHANNEL: "CREATE_EVOLUTIONS_RESPONSE",
    LIST_CHANNEL: "LIST_EVOLUTIONS",
    LIST_RESPONSE_CHANNEL: "LIST_EVOLUTIONS_RESPONSE",
    SHOW_CHANNEL: "SHOW_EVOLUTIONS",
    SHOW_RESPONSE_CHANNEL: "SHOW_EVOLUTIONS_RESPONSE",
    UPDATE_CHANNEL: "UPDATE_EVOLUTIONS",
    UPDATE_RESPONSE_CHANNEL: "UPDATE_EVOLUTIONS_RESPONSE",
    DESTROY_CHANNEL: "DESTROY_EVOLUTIONS",
    DESTROY_RESPONSE_CHANNEL: "DESTROY_EVOLUTIONS_RESPONSE",
  },

  BED: {
    CREATE_CHANNEL: "CREATE_BED_CHANNEL",
    CREATE_RESPONSE_CHANNEL: "CREATE_BED_CHANNEL_RESPONSE",
    LIST_CHANNEL: "LIST_BEDS",
    LIST_RESPONSE_CHANNEL: "LIST_BEDS_RESPONSE",
    UPDATE_CHANNEL: "UPDATE_BED_CHANNEL",
    UPDATE_RESPONSE_CHANNEL: "UPDATE_BED_CHANNEL_RESPONSE",
    SHOW_CHANNEL: "SHOW_BED_CHANNEL",
    SHOW_CHANNEL_RESPONSE: "SHOW_BED_CHANNEL_RESPONSE",
    DESTROY_RESPONSE: "DESTROY_BED_CHANNEL",
    DESTROY_RESPONSE_CHANNEL: "DESTROY_BED_CHANNEL_RESPONSE",
    LIST_NOT_IN_USE_CHANNEL: "LIST_BEDS_NOT_IN_USE",
    LIST_NOT_IN_USE_RESPONSE_CHANNEL: "LIST_BEDS_NOT_IN_USE_RESPONSE",
  },

  PDF: {
    REPORT_EVOLUTIONS: "PRINT_EVOLUTIONS_PDF",
    PRINT_EVOLUTIONS_RESPONSE: "PRINT_EVOLUTIONS_PDF_RESPONSE",

    REPORT_PACIENT_EVOLUTION: "PRINT_PACIENT_EVOLUTION",
    PRINT_PACIENT_EVOLUTION_RESPONSE: "PRINT_PACIENT_EVOLUTION_RESPONSE",
  },

  INTERNSHIP: {
    CREATE_CHANNEL: "CREATE_INTERNSHIP",
    CREATE_RESPONSE_CHANNEL: "CREATE_INTERNSHIP_RESPONSE",

    LIST_INTERNSHIPS: "LIST_INTERNSHIPS_CHANNEL",
    LIST_INTERNSHIPS_RESPONSE: "LIST_INTERNSHIPS_RESPONSE_CHANNEL",

    SHOW_INTERNSHIP_CHANNEL: "SHOW_INTERNSHIP_CHANNEL",
    SHOW_INTERNSHIP_RESPONSE_CHANNEL: "SHOW_INTERNSHIP_RESPONSE_CHANNEL",

    UPDATE_CHANNEL: "UPDATE_CHANNEL",
    UPDATE_CHANNEL_RESPONSE: "UPDATE_CHANNEL_RESPONSE",
  },
};
